---
- name: Creating configuration directory
  ansible.builtin.file:
    path: "{{ terminal_wezterm_config_file | dirname }}"
    state: directory
    mode: "0755"
    owner: "{{ common_user_name }}"
    group: "{{ common_user_group }}"

- name: Configuring Wezterm
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0644"
    owner: "{{ common_user_name }}"
    group: "{{ common_user_group }}"
  loop:
    - src: wezterm.lua.j2
      dest: "{{ terminal_wezterm_config_file }}"

- name: Installing Wezterm...
  tags: task_terminal
  become: true
  ansible.builtin.script: install_wezterm.sh
  args:
    creates: /usr/bin/wezterm
