---
- name: Running vscode setup...
  ansible.builtin.template:
    dest: "{{ common_user_home }}/.config/Code/User/settings.json"
    src: vscode.json.j2
    force: true
    mode: "0644"
    owner: "{{ common_user_name }}"
    group: "{{ common_user_group }}"
