---
bash_user_name: "{{ common_user_name }}"
bash_user_group: "{{ common_user_group }}"
bash_user_home: "{{ common_user_home }}"

bash_aliases_file: "{{ common_user_home }}/.bash_aliases"

bash_scripts_dir: "{{ bash_user_home }}/scripts"
bash_custom_scripts_dir: "{{ bash_user_home }}/custom_scripts"

bash_ps1_file: "{{ (bash_user_name == 'root') | ternary('02-ps1-root.sh', '02-ps1.sh') }}"

bash_exported_paths:
  - ~/bin
  - ~/{{ bash_custom_scripts_dir | basename }}
  - /usr/local/go/bin
