---
- name: Creating global functions
  ansible.builtin.template:
    src: profile.d/{{ item }}.j2
    dest: /etc/profile.d/{{ item }}
    mode: "0644"
  loop:
    - 50-include-paths.sh
  loop_control:
    label: /etc/profile.d/{{ item }}

- name: Importing tasks...
  ansible.builtin.import_tasks: user_bash.yml
  vars:
    bash_user_name: "{{ common_user_name }}"
    bash_user_group: "{{ common_user_group }}"
    bash_user_home: "{{ common_user_home }}"

- name: Importing tasks...
  ansible.builtin.import_tasks: user_bash.yml
  vars:
    bash_user_name: root
    bash_user_group: root
    bash_user_home: /root
    bash_ps1_file: ps1_root.sh

- name: Importing tasks...
  ansible.builtin.import_tasks: user_bash.yml
  vars:
    bash_user_name: "{{ common_user_name }}"
    bash_user_group: "{{ common_user_group }}"
    bash_user_home: "{{ common_user_home }}"

- name: Creating custom scripts dir
  ansible.builtin.file:
    path: "{{ bash_custom_scripts_dir }}"
    state: directory
    mode: "0755"
    owner: "{{ common_user_name }}"
    group: "{{ common_user_group }}"

- name: Creating flatpak run commands
  ansible.builtin.template:
    src: flatpak/cmd.sh.j2
    dest: "{{ bash_custom_scripts_dir }}/{{ item.alias }}"
    mode: "0755"
    owner: "{{ common_user_name }}"
    group: "{{ common_user_group }}"
  vars:
    bash_flatpak_cmd: "{{ item.cmd }}"
  loop: "{{ common_flatpak_apps }}"
  loop_control:
    label: "{{ bash_custom_scripts_dir }}/{{ item.alias }}"

- name: Creating tray icons
  ansible.builtin.template:
    src: tray/{{ item }}.sh.j2
    dest: "{{ bash_custom_scripts_dir }}/tray_{{ item }}"
    mode: "0755"
    owner: "{{ common_user_name }}"
    group: "{{ common_user_group }}"
  vars:
    bash_flatpak_cmd: "{{ item.cmd }}"
  loop:
    - audio_devices
  loop_control:
    label: "{{ bash_custom_scripts_dir }}/tray_{{ item }}"
