---
- name: Creating global functions
  ansible.builtin.template:
    src: profile.d/{{ item }}.j2
    dest: /etc/profile.d/{{ item }}
    mode: "0644"
  loop:
    - 50-include-paths.sh
  loop_control:
    label: /etc/profile.d/{{ item }}

- name: Importing tasks...
  ansible.builtin.import_tasks: user.yml

- name: Importing tasks...
  ansible.builtin.import_tasks: user.yml
  vars:
    bash_user_name: root
    bash_user_group: root
    bash_user_home: /root
