---
- name: Creating global functions
  ansible.builtin.template:
    src: profile.d/{{ item }}.j2
    dest: /etc/profile.d/{{ item }}
    mode: "0644"
  loop:
    - 50-include-paths.sh
  loop_control:
    label: /etc/profile.d/{{ item }}

- name: Creating environment and bash_aliases files
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0644"
    owner: "{{ common_user_name }}"
    group: "{{ common_user_group }}"
  loop:
    - src: bash/env.sh.j2
      dest: "{{ common_user_home }}/{{ bash_env_file }}"
    - src: bash/bash_aliases.sh.j2
      dest: "{{ common_user_home }}/.bash_aliases"

- name: Creating bash directories
  ansible.builtin.file:
    path: "{{ bash_dir }}"
    state: directory
    mode: "0755"
    owner: "{{ common_user_name }}"
    group: "{{ common_user_group }}"

- name: Creating bash files
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0644"
    owner: "{{ common_user_name }}"
    group: "{{ common_user_group }}"
  loop:
    - src: git-prompt.sh
      dest: "{{ bash_dir }}/.git-prompt.sh"
    - src: ps1.sh
      dest: "{{ bash_dir }}/.ps1.sh"
    - src: bash_custom.sh
      dest: "{{ bash_dir }}/.bash_custom.sh"
    - src: work_aliases.sh
      dest: "{{ bash_dir }}/.work_aliases.sh"
  loop_control:
    label: "{{ item.dest }}"

- name: Creating custom scripts dir
  ansible.builtin.file:
    path: "{{ bash_custom_scripts_dir }}"
    state: directory
    mode: "0755"
    owner: "{{ common_user_name }}"
    group: "{{ common_user_group }}"

- name: Creating flatpak run commands
  ansible.builtin.template:
    src: flatpak/cmd.sh.j2
    dest: "{{ bash_custom_scripts_dir }}/{{ item.alias }}"
    mode: "0755"
    owner: "{{ common_user_name }}"
    group: "{{ common_user_group }}"
  vars:
    bash_flatpak_cmd: "{{ item.cmd }}"
  loop: "{{ common_flatpak_apps }}"
  loop_control:
    label: "{{ bash_custom_scripts_dir }}/{{ item.alias }}"

- name: Creating tray icons
  ansible.builtin.template:
    src: tray/{{ item }}.sh.j2
    dest: "{{ bash_custom_scripts_dir }}/tray_{{ item }}"
    mode: "0755"
    owner: "{{ common_user_name }}"
    group: "{{ common_user_group }}"
  vars:
    bash_flatpak_cmd: "{{ item.cmd }}"
  loop:
    - audio_devices
  loop_control:
    label: "{{ bash_custom_scripts_dir }}/tray_{{ item }}"
