---
- name: Creating global functions
  ansible.builtin.template:
    src: profile.d/{{ item }}.j2
    dest: /etc/profile.d/{{ item }}
    mode: "0644"
  loop:
    - 50-include-paths.sh
  loop_control:
    label: /etc/profile.d/{{ item }}

- name: Configuring user...
  ansible.builtin.include_tasks: user.yml

- name: Copying custom programs
  ansible.builtin.copy:
    src: "bin/{{ item }}"
    dest: "{{ bash_custom_scripts_dir }}/{{ item }}"
    mode: "0644"
    owner: "{{ bash_user_name }}"
    group: "{{ bash_user_group }}"
  loop:
    - pulse
  loop_control:
    label: "{{ bash_scripts_dir }}/{{ item }}"

- name: Configuring root user...
  ansible.builtin.include_tasks: user.yml
  vars:
    bash_user_name: root
    bash_user_group: root
    bash_user_home: /root
