---
- name: Creating wallpapers directory
  ansible.builtin.file:
    path: "{{ common_wallpaper_dir }}"
    state: directory
    mode: "0755"

- name: Copying wallpapers
  ansible.builtin.copy:
    src: wallpapers/{{ item }}
    dest: "{{ common_wallpaper_dir }}/{{ item }}"
    mode: "0644"
  loop: "{{ wallpapers_list }}"
  loop_control:
    label: "{{ common_wallpaper_dir }}/{{ item }}"
