---
# Must be defined in every host
common_user_name: "{{ inventory_user.name }}"
common_user_group: "{{ inventory_user.group }}"
common_user_home: "{{ inventory_user.home }}"
common_user_email: "{{ inventory_user.email }}"
common_user_passwd: "{{ inventory_user.passwd }}"

common_user_config_dir: "{{ common_user_home }}/.config"

# Wallpaper config file
common_fehbg_file: "{{ common_user_home }}/.fehbg"

# Terminal config
common_picom_config_file: "{{ common_user_home }}/.config/picom/picom.conf"

# Apt default apps
common_apt_default_startup_apps:
  - /usr/bin/gnome-terminal
  - /usr/bin/code

# Expand on each host
common_apt_host_startup_apps: []
common_apt_startup_apps: "{{ common_apt_default_startup_apps + common_apt_host_startup_apps }}"

# Flatpak default apps
common_flatpak_excecutable: /usr/bin/flatpak
common_flatpak_default_apps:
  - name: Obsidian
    app: md.obsidian.Obsidian
    cmd: "{{ common_flatpak_excecutable }} run --file-forwarding md.obsidian.Obsidian @@u %U @@"
    alias: obsidian
    on_startup: true
  - name: Spotify
    app: com.spotify.Client
    cmd: "{{ common_flatpak_excecutable }} run --file-forwarding com.spotify.Client @@u %U @@"
    alias: spotify
    on_startup: false
  - name: ZapZap
    app: com.rtosta.zapzap
    cmd: "{{ common_flatpak_excecutable }} run --file-forwarding com.rtosta.zapzap @@u %u @@"
    alias: zapzap
    on_startup: true
  - name: Thunderbird
    app: org.mozilla.Thunderbird
    cmd: "{{ common_flatpak_excecutable }} run --file-forwarding org.mozilla.Thunderbird @@u %u @@"
    alias: thunderbird
    on_startup: true

# Expand on each host
common_flatpak_host_apps: []
common_flatpak_apps: "{{ common_flatpak_default_apps + common_flatpak_host_apps }}"
