galaxy_info:
  author: ndelucca
  namespace: ndelucca
  description: my main linux setup
  company: ndelucca
  license: BSD
  min_ansible_version: "8.2"

  # If this a Container Enabled role, provide the minimum Ansible Container version.
  # min_ansible_container_version:

  #
  # Provide a list of supported platforms, and for each platform a list of versions.
  # If you don't wish to enumerate all versions for a particular platform, use 'all'.
  # To view available platforms and versions (or releases), visit:
  # https://galaxy.ansible.com/api/v1/platforms/
  #
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - bookworm
        - bullseye
        - buster

  galaxy_tags: []

dependencies: []
