---
- name: Installing feh
  tags: install_apt
  ansible.builtin.apt:
    name: feh

- name: Creating wallpapers directory
  ansible.builtin.file:
    path: "{{ feh_wallpaper_dir }}"
    state: directory
    mode: "0755"
    owner: "{{ common_user_name }}"
    group: "{{ common_user_group }}"

- name: Copying wallpapers
  ansible.builtin.copy:
    src: wallpapers/{{ item }}
    dest: "{{ feh_wallpaper_dir }}/{{ item }}"
    mode: "0644"
    owner: "{{ common_user_name }}"
    group: "{{ common_user_group }}"
  loop: "{{ feh_wallpaper_list }}"
  loop_control:
    label: "{{ feh_wallpaper_dir }}/{{ item }}"

- name: Create .fehbg file
  ansible.builtin.template:
    src: fehbg.sh.j2
    dest: "{{ common_fehbg_file }}"
    mode: "0774"
    owner: "{{ common_user_name }}"
    group: "{{ common_user_group }}"
  notify: Reload feh
