---
ansible_host: localhost
ansible_connection: local
ansible_become_pass: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  31383539663464376166356434363934616632353936356433323337363639623932303563363962
  3330393266393039386665613532646262333536326633370a353261306665313332623665373033
  30663233306566663563353265616365313364663036393136316639633934656464366662303765
  3534373563643765370a643561383664666333386561376435366635656538316361343066376362
  3935

common_user_name: ndelucca
common_user_group: ndelucca
common_user_home: /home/ndelucca
common_user_email: ndelucca@educativa.com
common_user_passwd: "{{ ansible_become_pass }}"

i3_main_screen: HDMI-1
i3_secondary_screen: eDP-1

common_firefox_startup: false
common_chrome_startup: true

common_host_apps:
  - alias: edge
    name: Edge
    comment: Crap messaging app
    executable: "{{ common_user_bin_dir }}/edge"
    icon: com.microsoft.Edge
    launch_terminal: false
    startup: false
    startup_delay: 0
    flatpak: true
    flatpak_app: com.microsoft.Edge

  - alias: thunderbird
    name: Thunderbird
    comment: Email client
    executable: /usr/bin/thunderbird
    icon: thunderbird
    launch_terminal: false
    startup: false
    startup_delay: 8
    flatpak: false
    flatpak_app:

  - alias: dbeaver
    name: DBeaver
    comment: Database client
    executable: "{{ common_user_bin_dir }}/dbeaver"
    icon: io.dbeaver.DBeaverCommunity
    launch_terminal: false
    startup: false
    startup_delay: 0
    flatpak: true
    flatpak_app: io.dbeaver.DBeaverCommunity
