---

- name: Assuring shared images directory...
  ansible.builtin.file:
    path: "{{ grub_bg_image_location | dirname }}"
    state: directory
    mode: "0755"

- name: Copying grub background image...
  ansible.builtin.copy:
    src: "{{ grub_bg_image }}"
    dest: "{{ grub_bg_image_location }}"
    mode: "0644"

- name: Configuring grub...
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: "{{ item.regex }}"
    line: "{{ item.line }}"
  loop:
    - regex: ^GRUB_BACKGROUND
      line: GRUB_BACKGROUND={{ grub_bg_image_location }}
    - regex: ^GRUB_CMDLINE_LINUX_DEFAULT
      line: GRUB_CMDLINE_LINUX_DEFAULT="quiet"
    - regex: ^GRUB_TIMEOUT
      line: GRUB_TIMEOUT=2
  notify: Update grub
