---
- name: Selected configuration
  ansible.builtin.debug:
    msg: >-
      (gitea_version: {{ gitea_version }})
      (gitea_bin: {{ gitea_bin }})
      (gitea_envfile: {{ gitea_envfile }})
      (gitea_working_dir: {{ gitea_working_dir }})
      (gitea_user: {{ gitea_user }})
      (gitea_group: {{ gitea_group }})
      (gitea_download_url: {{ gitea_download_url }})
      (gitea_systemd_service_file: {{ gitea_systemd_service_file }})

- name: Creating gitea system group
  ansible.builtin.group:
    name: "{{ gitea_group }}"
    state: present

- name: Creating gitea system user
  ansible.builtin.user:
    name: "{{ gitea_user }}"
    group: "{{ gitea_group }}"
    home: "{{ gitea_working_dir }}"
    shell: "/bin/bash"
    comment: Gitea

- name: Creating gitea directory
  ansible.builtin.file:
    path: "{{ gitea_bin | dirname }}"
    state: directory
    owner: "{{ gitea_user }}"
    group: "{{ gitea_group }}"
    mode: "0755"
    recurse: true

- name: Downloading gitea binary
  ansible.builtin.get_url:
    url: "{{ gitea_download_url }}"
    dest: "{{ gitea_bin }}"
    owner: "{{ gitea_user }}"
    group: "{{ gitea_group }}"
    mode: "0755"

- name: Creating gitea.env file
  ansible.builtin.template:
    src: gitea.env.j2
    dest: "{{ gitea_envfile }}"
    mode: "0644"
  notify: Restart gitea

- name: Creating gitea systemd unit file
  ansible.builtin.template:
    src: gitea.unit.j2
    dest: "{{ gitea_systemd_service_file }}"
    mode: "0644"
  notify: Restart gitea

- name: Enabling and starting gitea web service
  ansible.builtin.systemd:
    name: gitea.service
    state: started
    enabled: true
