---
- name: Disabling and stoping gitea web service
  ansible.builtin.service:
    name: gitea
    state: stopped
    enabled: false

- name: Deleting gitea directory
  ansible.builtin.file:
    path: "{{ gitea_file }}"
    state: absent
  loop:
    - "{{ gitea_bin | dirname }}"
    - "{{ gitea_envfile }}"
    - "{{ gitea_systemd_service_file }}"
  loop_control:
    loop_var: gitea_file

- name: Deleting gitea system user
  ansible.builtin.user:
    name: "{{ gitea_user }}"
    state: absent

- name: Deleting gitea system group
  ansible.builtin.group:
    name: "{{ gitea_group }}"
    state: absent
