---
- name: Updating apt
  tags: update_apt
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Installing packages
  tags: install_apt
  ansible.builtin.apt:
    name:
      - i3
      - feh
