---
# Can't do it with normal repositories because Mr.Mint is oldie but goldie.
- name: Installing updated i3 .deb package
  tags: apt
  ansible.builtin.apt:
    deb: "{{ item }}"
  loop:
    - "{{ i3_wm_deb_url }}"
    - "{{ i3_deb_url }}"

- name: Updating apt
  tags: apt
  ansible.builtin.apt:
    cache_valid_time: 3600
    update_cache: true
    autoremove: true
    autoclean: true

- name: Creating custom scripts dir
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
    owner: "{{ common_user_name }}"
    group: "{{ common_user_group }}"
  loop:
    - "{{ i3_config_dir }}"
    - "{{ i3_config_subdir }}"
    - "{{ i3_status_dir }}"

- name: Creating i3 configuration file
  tags: cfg, i3cfg
  ansible.builtin.template:
    src: "i3/config.cfg.j2"
    dest: "{{ i3_config_dir }}/{{ item }}"
    mode: "0644"
    owner: "{{ common_user_name }}"
    group: "{{ common_user_group }}"
  loop:
    - config
  loop_control:
    label: "{{ i3_config_dir }}/{{ item }}"
  notify: Restart i3

- name: Creating i3 configuration files
  tags: cfg, i3cfg
  ansible.builtin.template:
    src: "i3/{{ item }}.j2"
    dest: "{{ i3_config_subdir }}/{{ item }}"
    mode: "0644"
    owner: "{{ common_user_name }}"
    group: "{{ common_user_group }}"
  loop:
    - 01-keybindings.cfg
    - 02-workspaces.cfg
    - 03-appearance.cfg
    - 04-exec.cfg
    - 05-modes.cfg
  loop_control:
    label: "{{ i3_config_dir }}/{{ item }}"
  notify: Restart i3

- name: Creating i3status configuration file
  tags: cfg, i3statuscfg
  ansible.builtin.template:
    src: "i3status/config.cfg.j2"
    dest: "{{ i3_status_dir }}/{{ item }}"
    mode: "0644"
    owner: "{{ common_user_name }}"
    group: "{{ common_user_group }}"
  loop:
    - config
  loop_control:
    label: "{{ i3_config_dir }}/{{ item }}"
  notify: Restart i3

- name: Creating gtk configuration files
  tags: cfg
  ansible.builtin.template:
    src: "{{ item.gtk_version }}/{{ item.gtk_file }}.j2"
    dest: "{{ common_user_config_dir }}/{{ item.gtk_version }}/{{ item.gtk_file }}"
    mode: "0664"
    owner: "{{ common_user_name }}"
    group: "{{ common_user_group }}"
  loop:
    - gtk_file: settings.ini
      gtk_version: gtk-3.0
    - gtk_file: settings.ini
      gtk_version: gtk-2.0
  loop_control:
    label: "{{ common_user_config_dir }}/{{ item.gtk_version }}/{{ item.gtk_file }}"
  notify: Restart i3

- name: Creating rofi configuration directory
  tags: rofi
  ansible.builtin.file:
    path: "{{ i3_rofi_config_file | dirname }}"
    state: directory
    mode: "0755"
    owner: "{{ common_user_name }}"
    group: "{{ common_user_group }}"

- name: Creating rofi configuration file
  tags: rofi
  ansible.builtin.template:
    src: "rofi/config.rasi.j2"
    dest: "{{ i3_rofi_config_file }}"
    mode: "0644"
    owner: "{{ common_user_name }}"
    group: "{{ common_user_group }}"
