---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: debian12
    image: docker.io/debian:bookworm
    privileged: true
    volume_mounts:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
  - name: debian11
    image: docker.io/debian:bullseye
    privileged: true
    volume_mounts:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
  - name: ubuntu22.04
    image: docker.io/ubuntu:22.04
    privileged: true
    volume_mounts:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"

provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
      callback_whitelist: profile_tasks, timer, yaml
    ssh_connection:
      pipelining: false

verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint .
