---
- name: Creating git configuration file...
  ansible.builtin.template:
    dest: "{{ common_user_home }}/.gitconfig"
    src: gitconfig.ini.j2
    mode: "0644"
    owner: "{{ common_user_name }}"
    group: "{{ common_user_group }}"
