---
- name: OS Check
  hosts: my_machines
  gather_facts: true

  tasks:

    - name: Distribution
      ansible.builtin.debug:
        msg: "{{ ansible_distribution }}"

    - name: Distribution version
      ansible.builtin.debug:
        msg: "{{ ansible_distribution_version }}"

    - name: Distribution major version
      ansible.builtin.debug:
        msg: "{{ ansible_distribution_major_version }}"
