---
- name: Installing NVM and Node.js
  hosts: my_machines
  become: true
  become_user: "{{ user.name }}"

  tasks:
    - name: Creating .bashrc_custom file
      ansible.builtin.file:
        path: "{{ user.home }}/.bashrc_custom"
        state: touch
        owner: "{{ user.name }}"
        group: "{{ user.group }}"
        mode: "0755"

    - name: Importing stephdewit.nvm role
      ansible.builtin.import_role:
        name: stephdewit.nvm
      vars:
        nvm_node_version: lts
        nvm_install_path: "{{ user.home }}/.nvm"
        nvm_shell_init_file: "{{ user.home }}/.bashrc_custom"
      environment:
        NVM_DIR: "{{ user.home }}/.nvm"
