---
- name: Installing NVM and Node.js
  hosts: my_machines
  become: true
  become_user: "{{ common_user_name }}"

  tasks:
    - name: Creating .bashrc_custom file
      ansible.builtin.file:
        path: "{{ common_user_home }}/scripts/06-nvm.sh"
        state: touch
        owner: "{{ common_user_name }}"
        group: "{{ common_user_group }}"
        mode: "0755"

    - name: Importing stephdewit.nvm role
      ansible.builtin.import_role:
        name: stephdewit.nvm
      vars:
        nvm_node_version: lts
        nvm_install_path: "{{ common_user_home }}/.nvm"
        nvm_shell_init_file: "{{ common_user_home }}/scripts/06-nvm.sh"
      environment:
        NVM_DIR: "{{ common_user_home }}/.nvm"
