---
i3_config_dir: "{{ common_user_config_dir }}/i3"
i3_config_subdir: "{{ i3_config_dir }}/config.d"
i3_config_font: JetBrains Mono 10
i3_config_mod: Mod4

i3_status_dir: "{{ common_user_config_dir }}/i3status"

# i3 Installation
i3_version: 4.22-2
i3_wm_deb_url: "http://ftp.debian.org/debian/pool/main/i/i3-wm/i3-wm_{{ i3_version }}_amd64.deb"
i3_deb_url: "http://ftp.debian.org/debian/pool/main/i/i3-wm/i3_{{ i3_version }}_amd64.deb"

# GTK Configuration
i3_gtk2_config_dir: "{{ common_user_config_dir }}/gtk-2.0/"
i3_gtk3_config_dir: "{{ common_user_config_dir }}/gtk-3.0/"

i3_gtk_theme_name: Mint-Y-Dark
i3_gtk_icon_theme_name: Mint-Y
i3_gtk_cursor_theme_name: Bibata-Modern-Ice

i3_color_scheme:
  background: "#1e1e1e"
  foreground: "#e8e8e8"
  active_workspace: "#044535"
  inactive_workspace: "#242424"
  urgent_workspace: "#6f2b0b"
  status_good: "#448575"
  status_degraded: "#f0d050"
  status_bad: "#ef3b3b"
