---
- name: Installing feh
  ansible.builtin.apt:
    name: feh
    state: present

- name: Create .fehbg file
  ansible.builtin.template:
    src: feh/fehbg.sh.j2
    dest: "{{ common_fehbg_file }}"
    mode: "0774"
    owner: "{{ common_user_name }}"
    group: "{{ common_user_group }}"
  notify: Reload feh
