---
- name: Installing fzf
  ansible.builtin.apt:
    name:
      - fd-find
      - fzf
    state: present

- name: Creating fzf config
  ansible.builtin.template:
    dest: "{{ common_user_home }}/.ignore"
    src: fzf/ignore.j2
    force: true
    mode: "0644"
    owner: "{{ common_user_name }}"
    group: "{{ common_user_group }}"
