---
- name: Deleting bloat packages and security risks
  tags: task_apt
  ansible.builtin.apt:
    state: absent
    name:
      - vim.tiny
      - vlc
      - gimp
      - onboard
      - celluloid
      - hypnotix
      - rhythmbox
      - mono-runtime-common # security risk
      - gnome-orca # security risk
      - orca # security risk

- name: Installing common apps
  ansible.builtin.apt:
    name: "{{ item.alias }}"
    state: present
  loop: "{{ common_apt_source_apps }}"
  loop_control:
    label: "{{ item.alias }}"

- name: Installing common apps by .deb package
  ansible.builtin.apt:
    deb: "{{ item.deb }}"
    state: present
  loop: "{{ common_apt_deb_apps }}"
  loop_control:
    label: "{{ item.alias }}"

- name: Installing packages
  tags: task_apt
  ansible.builtin.apt:
    name:
      - python3-pip
      - pipx
      - gawk
      - direnv
      - virt-manager
      - inkscape
      - gpick # color picker from screen
      - cowsay
      - fortune-mod
      - shellcheck

- name: Importing tasks
  ansible.builtin.import_tasks: flatpak.yml
  tags: tasks_flatpak

- name: Importing tasks
  ansible.builtin.import_tasks: autostart.yml
  tags: tasks_autostart

- name: Importing tasks
  ansible.builtin.import_tasks: picom.yml
  tags: tasks_picom

- name: Importing tasks
  ansible.builtin.import_tasks: lightdm.yml
  tags: tasks_lightdm

- name: Importing tasks
  ansible.builtin.import_tasks: feh.yml
  tags: tasks_feh

- name: Importing tasks
  ansible.builtin.import_tasks: mycli.yml
  tags: tasks_mycli

- name: Importing tasks
  ansible.builtin.import_tasks: fzf.yml
  tags: tasks_fzf
