---
- name: Deleting default packages
  tags: task_apt
  ansible.builtin.apt:
    state: absent
    name: "{{ pkg }}"
  loop:
    - vim.tiny
    - vlc
    - gimp
    - onboard
    - mono-runtime-common # security risk
    - gnome-orca # security risk
    - orca # security risk
  loop_control:
    loop_var: pkg

- name: Installing packages
  tags: task_apt
  ansible.builtin.apt:
    name: "{{ pkg }}"
  loop:
    - python3-pip
    - code
    - firefox
    - pipx
    - ranger
    - gawk
    - direnv
    - virt-manager
    - mycli
    - inkscape
    - numlockx
    - redshift
    - cowsay
    - fortune-mod
    - shellcheck
  loop_control:
    loop_var: pkg

- name: Installing flatpaks
  tags: task_flatpak
  community.general.flatpak:
    name: "{{ pkg.app }}"
    state: present
  loop: "{{ common_flatpak_apps }}"
  loop_control:
    loop_var: pkg
    label: "{{ pkg.app }}"
  become: true
  become_user: "{{ common_user_name }}"

- name: Importing tasks
  ansible.builtin.import_tasks: mycli.yml

- name: Importing tasks
  ansible.builtin.import_tasks: redshift.yml
