---
- name: Deleting default packages
  tags: task_apt
  ansible.builtin.apt:
    state: absent
    name: "{{ pkg }}"
  loop:
    - vim.tiny
    - vlc
    - gimp
    - onboard
    - mono-runtime-common # security risk
    - gnome-orca # security risk
    - orca # security risk
  loop_control:
    loop_var: pkg

- name: Installing packages
  tags: task_apt
  ansible.builtin.apt:
    name: "{{ pkg }}"
  loop:
    - python3-pip
    - fd-find
    - fzf
    - feh
    - code
    - firefox
    - pipx
    - ranger
    - gawk
    - direnv
    - virt-manager
    - mycli
    - inkscape
    - numlockx
    - redshift
    - cowsay
    - fortune-mod
    - shellcheck
    - picom
    - thunderbird
  loop_control:
    loop_var: pkg

- name: Importing tasks
  ansible.builtin.import_tasks: flatpak.yml
  tags: tasks_flatpak

- name: Importing tasks
  ansible.builtin.import_tasks: autostart.yml
  tags: tasks_autostart

- name: Importing tasks
  ansible.builtin.import_tasks: lightdm.yml
  tags: tasks_lightdm

- name: Importing tasks
  ansible.builtin.import_tasks: feh.yml
  tags: tasks_feh

- name: Importing tasks
  ansible.builtin.import_tasks: mycli.yml
  tags: tasks_mycli

- name: Importing tasks
  ansible.builtin.import_tasks: redshift.yml
  tags: tasks_redshift

- name: Importing tasks
  ansible.builtin.import_tasks: fzf.yml
  tags: tasks_fzf
