---
- name: Installing mycli
  ansible.builtin.apt:
    name: mycli
    state: present

- name: Creating mycli config
  ansible.builtin.template:
    dest: "{{ common_user_home }}/.my.cnf"
    src: mycli/mycli.cnf.j2
    force: true
    mode: "0644"
    owner: "{{ common_user_name }}"
    group: "{{ common_user_group }}"
