---
- name: Creating fonts directory
  ansible.builtin.file:
    state: directory
    path: "{{ fonts_path }}"
    mode: "0755"
    owner: "{{ common_user_name }}"
    group: "{{ common_user_group }}"

- name: Running mscorefonts terms and conditions hack
  when: ansible_distribution == "Linux Mint"
  ansible.builtin.debconf:
    name: ttf-mscorefonts-installer
    question: msttcorefonts/accepted-mscorefonts-eula
    value: "true"
    vtype: select

- name: Running mscorefonts terms and conditions hack
  when: ansible_distribution == "Linux Mint"
  ansible.builtin.debconf:
    name: ttf-mscorefonts-installer
    question: msttcorefonts/present-mscorefonts-eula
    value: ""
    vtype: select

- name: Installing apt mscorefonts
  when: ansible_distribution == "Linux Mint"
  ansible.builtin.apt:
    name: "{{ font_pkg }}"
  loop:
    - ttf-mscorefonts-installer
  loop_control:
    loop_var: font_pkg

- name: Installing apt fonts
  ansible.builtin.apt:
    name: "{{ font_pkg }}"
  loop:
    - fonts-font-awesome
  loop_control:
    loop_var: font_pkg

- name: Creating nerdfonts directory
  ansible.builtin.file:
    path: "{{ fonts_path }}/fonts-nerd-fonts/"
    state: directory
    mode: "0755"
    owner: "{{ common_user_name }}"
    group: "{{ common_user_group }}"

- name: Installing nerdfonts
  ansible.builtin.include_tasks: install_nerd_font.yml
  vars:
    fonts_nerdfont_name: "{{ item }}"
  loop:
    - JetBrainsMono
    - EnvyCodeR
